import SwiftUI
import SwiftData

struct LectureDetailView: View {
    @Environment(\.modelContext) private var modelContext
    @Bindable var lecture: Lecture

    @State private var showingDeleteAlert = false

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 24) {
                header
                notesSection
                transcriptSection
                attachmentsSection
                analyzeSection
            }
            .padding()
        }
        .navigationTitle(lecture.title)
        .toolbar {
            ToolbarItem(placement: .destructiveAction) {
                Button(role: .destructive) {
                    showingDeleteAlert = true
                } label: {
                    Label("Delete", systemImage: "trash")
                }
            }
        }
        .alert("Delete Lecture?", isPresented: $showingDeleteAlert) {
            Button("Delete", role: .destructive) {
                if let course = lecture.course {
                    course.lectures.removeAll { $0.id == lecture.id }
                    course.touchUpdatedAt()
                }
                modelContext.delete(lecture)
                try? modelContext.save()
            }
            Button("Cancel", role: .cancel) { }
        } message: {
            Text("This will remove the lecture and its generated notes.")
        }
    }

    private var header: some View {
        VStack(alignment: .leading, spacing: 8) {
            Text(lecture.formattedDate)
                .font(.headline)
            Text(lecture.summary.isEmpty ? "No summary generated yet." : lecture.summary)
                .font(.subheadline)
                .foregroundStyle(.secondary)
        }
        .frame(maxWidth: .infinity, alignment: .leading)
    }

    private var notesSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            Label("Notes", systemImage: "note.text")
                .font(.title3.weight(.semibold))
            if lecture.noteSections.isEmpty {
                Text("Notes generated by AI will appear here. Use the button below to kick things off.")
                    .foregroundStyle(.secondary)
            } else {
                ForEach(Array(lecture.noteSections.enumerated()), id: \.offset) { index, entry in
                    VStack(alignment: .leading, spacing: 8) {
                        HStack(alignment: .top, spacing: 12) {
                            Text(String(format: "%02d", index + 1))
                                .font(.caption.monospacedDigit())
                                .padding(8)
                                .background(.thinMaterial, in: RoundedRectangle(cornerRadius: 12))
                            Text(entry)
                        }
                        Button(role: .destructive) {
                            lecture.noteSections.remove(at: index)
                            try? modelContext.save()
                        } label: {
                            Label("Delete Note", systemImage: "trash")
                        }
                        .tint(.red)
                    }
                    .padding(.vertical, 4)
                }
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
    }

    private var transcriptSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            Label("Transcript", systemImage: "waveform")
                .font(.title3.weight(.semibold))
            Text(lecture.transcript.isEmpty ? "Audio to text transcription will be stored here once implemented." : lecture.transcript)
                .font(.body)
                .foregroundStyle(.secondary)
        }
        .frame(maxWidth: .infinity, alignment: .leading)
    }

    private var attachmentsSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            Label("Attachments", systemImage: "paperclip")
                .font(.title3.weight(.semibold))
            if lecture.audioResourcePath == nil && lecture.slideResourcePath == nil {
                Text("Upload audio recordings or slide PDFs to enrich AI processing results.")
                    .foregroundStyle(.secondary)
            }
            if let audio = lecture.audioResourcePath {
                Label(audio, systemImage: "waveform.circle")
            }
            if let slides = lecture.slideResourcePath {
                Label(slides, systemImage: "doc.richtext")
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
    }

    private var analyzeSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            Label("Analyze with AI", systemImage: "sparkles")
                .font(.title3.weight(.semibold))
            Text("Trigger a server-side pipeline that uploads audio, summarizes content, and stores flashcards.")
                .foregroundStyle(.secondary)
            Button {
                Task {
                    // Replace this Task with calls to your AI microservice once ready.
                    try? await Task.sleep(for: .seconds(1))
                }
            } label: {
                Label("Analyze with AI", systemImage: "wand.and.stars")
                    .frame(maxWidth: .infinity)
            }
            .buttonStyle(.borderedProminent)
        }
        .frame(maxWidth: .infinity, alignment: .leading)
    }
}

#Preview("Lecture Detail") {
    NavigationStack {
        if let lecture = try? PreviewBootstrap.previewContainer.mainContext.fetch(FetchDescriptor<Lecture>()).first {
            LectureDetailView(lecture: lecture)
        }
    }
    .modelContainer(PreviewBootstrap.previewContainer)
}
